### ISSUE TITLE
'Twowayshooting' doesn't run (for TIS simulation)

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#807]
Hi, 
I am trying to sample an interface using TIS simulation. I did the same using Oneway shooting Strategy of OPS and it works fine (example attached).
When I use Twoway shooting (example attached), it does not work. By this I mean that there is no explicit error but the MD simulation is not running. I tried thinking all obvious issues but could not resolve it. Will be glad if someone can give me a hint of the issue 
[TIS_twoway_issue.zip](https://github.com/openpathsampling/openpathsampling/files/2572426/TIS_twoway_issue.zip)

To run one way shooting , 
`nohup ./tis_ow_setup.py > log_1way &`

To run two way shooting , 
`nohup ./tis_tw_setup.py > log_2way &`

**Comment by dwhswenson** [comment]
1. Do **NOT** use OPS 0.9.3 with 2-way shooting. There was a major bug in 2-way shooting that was fixed in 0.9.4 (#752). (And if you're starting something new, you should update to a newer version anyway -- we're at 0.9.6 now!)

2. When I run your script (with a current dev version), I get an error caused by never getting one of the ensembles filled:

```
$ ./tis_tw_setup.py
# trying strategy #1 `get`: still missing 1 samples
?
# trying strategy #2 `split`: still missing 1 samples
?
4
8
7
7
6
Missing ensembles:
*  [liquid->crystal 0]
No extra ensembles.
Traceback (most recent call last):
  File "./tis_tw_setup.py", line 213, in <module>
    gausian_simulation = paths.PathSampling(storage, two_way_scheme, initial_conditions)
  File "/Users/dwhs/Dropbox/msm-tis/openpathsampling/pathsimulators/path_sampling.py", line 76, in __init__
    template_trajectory = self.sample_set.samples[0].trajectory
IndexError: list index out of range
```

The main problem I'm seeing is that the "liquid->crystal 0" ensemble never gets an initial trajectory, so the initial conditions are incomplete.

**Comment by dwhswenson** [comment]
I also get the same problem with the 1-way shooting. Did you include the correct initial trajectory in the zip file?

**Comment by arjunwadhawan** [comment]
Hi David 

1- Reason for using older version is that I started this TIS calculations way back (for other interfaces). So for consistency, using the same version. 
2- Yes, the initial trajectory is right and seem to work on 0.9.3 for 1 way shooting

**Comment by dwhswenson** [comment]
You ***must not*** use 0.9.3 for 2-way shooting. The implementation was wrong, and your results will be wrong.

In 0.9.4, I could run your scripts for both one-way and two-way (at least, I saw some output from an OpenMM reporter -- then hit ^C since I'm running on my laptop).

My best guess (don't have time to look into it now) is that the problem with your input trajectory in later versions (couldn't get it to run in anything from 0.9.5 later) may be related to the bug about volume boundaries that we fixed in #772. This could matter if your CV returns integer values and you put the interface/state barrier exactly on those values (instead of, e.g., $\lambda - 0.5$).

I would strongly recommend that, if you have to change anything, you use the most recent version.

**Comment by arjunwadhawan** [comment]
Hi,

I am using  0.9.4 but still have same issue. The MD simulations are not running. OpenMM reporter stops at following (means initialisation is right & the initial trajectory satisfy the conditions ). 

> No missing ensembles.
> Working on Monte Carlo cycle number 1
> Starting simulation...
> Working on first step

My question is that is there something wrong in the Twoway shooting script ? Why doesn't the MD run ?

**Comment by dwhswenson** [comment]
I can't reproduce this problem. Maybe the issue is with another package that doesn't match the version I'm using (I'm a few months behind on most things, although my OpenMM is much older, at 7.1.1).

The only change I made to your script was to comment out the (unused) spring shooting import (I don't have that installed here). Then I run:

```
~/Downloads/TIS_twoway_issue dwhs$ python -c "import openpathsampling as paths; print paths.git_HEAD()"
2a1bfab2e1ce79a05e8d332a0f60fc85762fba18
```
This confirms that I'm using the [release at v0.9.4](https://github.com/openpathsampling/openpathsampling/releases/tag/v0.9.4) (you can compare the commit hash). On to the script:

```
~/Downloads/TIS_twoway_issue dwhs$ python ./tis_tw_setup.py
# trying strategy #1 `get`: still missing 1 samples
?
2
4
8
7
7
6
No missing ensembles.
Working on Monte Carlo cycle number 1
Starting simulation...
Working on first step
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simtk/unit/quantity.py:438: RuntimeWarning: divide by zero encountered in double_scalars
  return Quantity(pow(self._value, exponent), pow(self.unit, exponent))
/Users/dwhs/Dropbox/mdtraj/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting unitcell_vectors dtype=float64 to <type 'numpy.float32'>
  TypeCastPerformanceWarning)
6
#"Step"	"Time (ps)"	"Potential Energy (kJ/mole)"	"Temperature (K)"	"Box Volume (nm^3)"	"Speed (ns/day)"
3	0.006	-171142.6158	284.093090467	122.579913433	0
6
6	0.012	-170970.139504	281.379168263	122.579913433	0.259
5
9	0.018	-171129.217752	283.198648521	122.579913433	0.264
5
12	0.024	-171116.38372	283.325660159	122.579913433	0.263
6
Working on Monte Carlo cycle number 2
Running for 22 seconds - 22.91 seconds per step
Estimated time remaining: 1 minute 31 seconds
```

Stopping the output here, but it ran to the end. I re-ran it several times, with no problems.

**Comment by arjunwadhawan** [comment]
David, if you don't mind, can you send me the clone of your conda environment where this simulation works? 

I still cant make it to run with OPS 0.9.4, openmm 7.1.1, Python=2.7

`conda env export > environment.yml  `

**Comment by arjunwadhawan** [comment]
Hi David, 
I rather moved to OPS 0.9.6 and changed the definition of interfaces and stable states from discrete numbers (based on your above comments).

I use OPENMM 7.1.1. It works for 1 way shooting but 2 way shooting still doesn't work. This is very strange to me. 

When moving to OPENMM 7.2, both 1way and 2way script works fine. 

Issue is I cannot move to openmm 7.2 for production run as we dont have CUDA 9 available on GPUs right now.

**Comment by dwhswenson** [comment]
Does it hang or does it exit? That doesn't look like there was a clean exit. If that's the case, you can always see where it hangs by sending a sigterm (type ctrl-C, or if it is running in the background, use the `kill` command) to stop it and give you the stack trace.

**Comment by dwhswenson** [comment]
Following up to summarize in-person conversation today:

Currently, the main problem appears to be that old trajectories used one device index, whereas @arjunwadhawan is now running on a different device index. For simplicity, let's say the old engine was `0`, and the new engine was `1`. The snapshot modifier needs access to its `.engine` attribute to apply constraints. This leads to the old engine trying to claim GPU device `0`, which is already in use (other work happening simultaneously on the node). But the actual dynamics are being done by an engine running on `1`.

This leads to the path mover rejecting the move because of NaN. My best guess is that something returns NaN when the shooting point modifier tries to use apply constraints using the old engine on device `0` (which is not available). This leads to NaN-rejected moves.

My suggestion was that @arjunwadhawan reorder the events in:

https://github.com/openpathsampling/openpathsampling/blob/ae85efda64a0f9047cec271b8b8a24f460f0897c/openpathsampling/snapshot_modifier.py#L153-L159

such that the `copy_with_replacement` comes after the engine, and includes replacing the engine. However, I'm concerned that the original `copy` method (within `copy_with_replacement`) might already start up the old engine.

@jhprinz: Any suggestions here? We've previously discussed the need to separate the device index, etc, from our engines.

Related: #651 #769
